name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Print env
      run: |
        echo github.event.action: ${{ github.event.action }}
        echo github.event_name: ${{ github.event_name }}
    
    - name: Install g++
      run: |
        sudo apt update
        sudo apt install g++
        g++ --version
        
    - name: Run Lab05
      run: |
        cd ./Lab/KTLT_Lab05
        g++ lab05.cpp
        ./a.out
